name = "Terranova Server"
author = "Lightning323"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f333a8d2f757b92e4dc30486e97e194ae4fb39241e1feeaad9a1e156fb1527fa"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
