name = "Terranova Server"
author = "Lightning323"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db1d45e5fe2e419b45ed12da94335049a0a228bed05ba33128840ccec88dbf7e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
