name = "Terranova Server"
author = "Lightning323"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2b8abb8d2c81006eae6dea9faf70ef791812e65cfb76f38af6be39e4238ac16"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
