#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Aug 12 15:00:37 MDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=Mellow Shader v3.1.zip
