name = "Terranova"
author = "Lightning323"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a7c26b6a7b726c655c6429176f15d083d2385f563e0b19d3cc338875fa83b8e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
