name = "Terranova"
author = "Lightning323"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8bf2809dd662206c4945cb95d8d13234e6ae9c6c8bab8bed8644bc17b7d58e4f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
