name = "Terranova"
author = "Lightning323"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab9f12c56c943183d3fccf89f0dc70ab22b73a2d2fb5e214315531a2b59a815a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
